-- Workout history: sessions + one row per completed set.
-- Additive only. exercises.completed_sets / last_completed_date stay in place
-- (no longer written by the app) so a rollback to the previous code still works.

CREATE TABLE public.workout_sessions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT workout_sessions_id_user_key UNIQUE (id, user_id),
  CONSTRAINT workout_sessions_completed_at_chk
    CHECK ((status = 'completed') = (completed_at IS NOT NULL))
);

CREATE INDEX workout_sessions_user_started_idx
  ON public.workout_sessions (user_id, started_at DESC);
-- At most one active session per user.
CREATE UNIQUE INDEX workout_sessions_one_active_idx
  ON public.workout_sessions (user_id) WHERE status = 'active';

CREATE TABLE public.set_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id UUID NOT NULL,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  exercise_id UUID REFERENCES public.exercises(id) ON DELETE SET NULL,
  -- Snapshot so history survives renaming or deleting the exercise.
  exercise_name TEXT NOT NULL,
  area TEXT NOT NULL,
  set_number INTEGER NOT NULL CHECK (set_number > 0),
  weight NUMERIC NOT NULL CHECK (weight >= 0),
  reps INTEGER NOT NULL CHECK (reps > 0),
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Generated by the client per tap; retries reuse it so a set is never logged twice.
  client_event_id UUID NOT NULL,
  -- A set can only belong to a session of the same user.
  CONSTRAINT set_logs_session_owner_fkey FOREIGN KEY (session_id, user_id)
    REFERENCES public.workout_sessions (id, user_id) ON DELETE CASCADE,
  CONSTRAINT set_logs_user_event_key UNIQUE (user_id, client_event_id)
);

CREATE INDEX set_logs_session_exercise_idx
  ON public.set_logs (session_id, exercise_id, set_number);
CREATE INDEX set_logs_exercise_id_idx ON public.set_logs (exercise_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.workout_sessions TO authenticated;
GRANT ALL ON public.workout_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.set_logs TO authenticated;
GRANT ALL ON public.set_logs TO service_role;

ALTER TABLE public.workout_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.set_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own workout sessions" ON public.workout_sessions
  FOR ALL USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "Users manage own set logs" ON public.set_logs
  FOR ALL USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);

-- Sessions idle for 4h are closed at the time of their last set.
CREATE OR REPLACE FUNCTION public.close_stale_sessions()
RETURNS void
LANGUAGE sql
SECURITY INVOKER
SET search_path = public
AS $$
  UPDATE workout_sessions s
  SET status = 'completed',
      completed_at = coalesce(
        (SELECT max(l.completed_at) FROM set_logs l WHERE l.session_id = s.id),
        s.started_at)
  WHERE s.user_id = auth.uid()
    AND s.status = 'active'
    AND coalesce(
      (SELECT max(l.completed_at) FROM set_logs l WHERE l.session_id = s.id),
      s.started_at) < now() - interval '4 hours';
$$;

-- Atomic, idempotent "סיימתי סט". Returns
-- { session_id, set_number, target_sets, finished } where finished means a full
-- round of the exercise's sets was just completed.
CREATE OR REPLACE FUNCTION public.log_set(p_exercise_id UUID, p_client_event_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_ex exercises%ROWTYPE;
  v_log set_logs%ROWTYPE;
  v_session UUID;
  v_n INTEGER;
  v_target INTEGER;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;

  -- Serialize all set logging for this user (double taps, two tabs).
  PERFORM pg_advisory_xact_lock(hashtext('log_set:' || v_uid::text));

  -- Retry of an event that already succeeded: return the original result.
  SELECT * INTO v_log FROM set_logs
  WHERE user_id = v_uid AND client_event_id = p_client_event_id;
  IF FOUND THEN
    SELECT sets INTO v_target FROM exercises WHERE id = v_log.exercise_id;
    v_target := greatest(coalesce(v_target, v_log.set_number), 1);
    RETURN jsonb_build_object(
      'session_id', v_log.session_id,
      'set_number', v_log.set_number,
      'target_sets', v_target,
      'finished', v_log.set_number % v_target = 0);
  END IF;

  SELECT * INTO v_ex FROM exercises WHERE id = p_exercise_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'exercise not found' USING ERRCODE = 'P0002';
  END IF;

  PERFORM close_stale_sessions();

  SELECT id INTO v_session FROM workout_sessions
  WHERE user_id = v_uid AND status = 'active';
  IF v_session IS NULL THEN
    INSERT INTO workout_sessions (user_id) VALUES (v_uid) RETURNING id INTO v_session;
  END IF;

  SELECT count(*) + 1 INTO v_n FROM set_logs
  WHERE session_id = v_session AND exercise_id = p_exercise_id;

  INSERT INTO set_logs
    (session_id, user_id, exercise_id, exercise_name, area, set_number, weight, reps, client_event_id)
  VALUES
    (v_session, v_uid, v_ex.id, v_ex.name, v_ex.area, v_n, v_ex.weight, v_ex.reps, p_client_event_id);

  v_target := greatest(v_ex.sets, 1);
  RETURN jsonb_build_object(
    'session_id', v_session,
    'set_number', v_n,
    'target_sets', v_target,
    'finished', v_n % v_target = 0);
END;
$$;

-- The active session (after closing stale ones) with sets done per exercise, or null.
CREATE OR REPLACE FUNCTION public.get_active_session()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_s workout_sessions%ROWTYPE;
BEGIN
  PERFORM close_stale_sessions();
  SELECT * INTO v_s FROM workout_sessions
  WHERE user_id = auth.uid() AND status = 'active';
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  RETURN jsonb_build_object(
    'id', v_s.id,
    'started_at', v_s.started_at,
    'total_sets', (SELECT count(*) FROM set_logs WHERE session_id = v_s.id),
    'counts', coalesce(
      (SELECT jsonb_object_agg(exercise_id, n)
       FROM (SELECT exercise_id, count(*) AS n FROM set_logs
             WHERE session_id = v_s.id AND exercise_id IS NOT NULL
             GROUP BY exercise_id) c),
      '{}'::jsonb));
END;
$$;

CREATE OR REPLACE FUNCTION public.finish_session(p_session_id UUID)
RETURNS VOID
LANGUAGE sql
SECURITY INVOKER
SET search_path = public
AS $$
  UPDATE workout_sessions
  SET status = 'completed', completed_at = now()
  WHERE id = p_session_id AND user_id = auth.uid() AND status = 'active';
$$;

-- Seeds the default exercises once, only for a user with none. The advisory
-- lock makes concurrent first loads safe without a uniqueness constraint.
CREATE OR REPLACE FUNCTION public.seed_default_exercises(p_rows JSONB)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_count INTEGER;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext('seed_exercises:' || v_uid::text));
  IF EXISTS (SELECT 1 FROM exercises WHERE user_id = v_uid) THEN
    RETURN 0;
  END IF;
  INSERT INTO exercises (user_id, area, name, weight, reps, sets, sort_order)
  SELECT v_uid, r->>'area', r->>'name', (r->>'weight')::numeric,
         (r->>'reps')::integer, (r->>'sets')::integer, (t.ord - 1)::integer
  FROM jsonb_array_elements(p_rows) WITH ORDINALITY AS t(r, ord);
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.close_stale_sessions() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.log_set(UUID, UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_active_session() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.finish_session(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.seed_default_exercises(JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.close_stale_sessions() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.log_set(UUID, UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_active_session() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.finish_session(UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.seed_default_exercises(JSONB) TO authenticated, service_role;
